language: cpp

sudo: required
dist: trusty

branches:
  only:
    - master


env:
  - BUILD_TYPE=Release BOOSTREGEX=ON
  - BUILD_TYPE=Debug BOOSTREGEX=ON

matrix:
  include:
  - os: osx
    compiler: clang
    env: BOOSTREGEX=OFF
    before_install:
    - brew update
    - brew install
        sdl2
        sdl2_image
        sdl2_mixer
        sdl2_ttf


before_install:
  - sudo apt-get install -y
      libboost-regex-dev
      libsdl2-dev
      libsdl2-image-dev
      libsdl2-mixer-dev
      libsdl2-ttf-dev

before_script:
  - $CXX --version
  - cmake --version
  - sdl2-config --version

script:
  - mkdir build && cd build
  - cmake ..
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DUSE_BOOST_REGEX=${BOOSTREGEX}
  - make VERBOSE=1
  - if [[ $BUILD_TYPE == Debug ]]; then
      ./tests/openblok_test;
    fi
